  name: Delövning 1 - Minimal Pipeline
  
  on: workflow_dispatch
  # ska startas manuellt
  
  jobs:
    print-info:
      runs-on: ubuntu-latest # vilken runner?
      steps:
        - name: Kommando som visar att pipelinen har startats # namnge steget
          run: echo "Pipelinen är igång." # vad som ska göras
        - name: Python version
          run: python --version